export const cars = [
  // Sedans
  {
    imageUrl: "/cars/car_types/sedan/camry.jpeg",
    type: "Sedan",
    make: "Toyota",
    model: "Camry",
    year: "2012",
    color: "white",
  },
  {
    imageUrl: "/cars/car_types/sedan/accord.jpeg",
    type: "Sedan",
    make: "Honda",
    model: "Accord",
    year: "2010",
    color: "white",
  },
  {
    imageUrl: "/cars/car_types/sedan/corolla.jpeg",
    type: "Sedan",
    make: "Toyota",
    model: "Corolla",
    year: "2002",
    color: "red",
  },
  {
    imageUrl: "/cars/car_types/sedan/fusion.jpeg",
    type: "Sedan",
    make: "Ford",
    model: "Fusion",
    year: "2011",
    color: "red",
  },
  {
    imageUrl: "/cars/car_types/sedan/sentra.jpeg",
    type: "Sedan",
    make: "Nissan",
    model: "Sentra",
    year: "2022",
    color: "white",
  },
  {
    imageUrl: "/cars/car_types/sedan/cruze.jpeg",
    type: "Sedan",
    make: "Chevrolet",
    model: "Cruze",
    year: "2015",
    color: "silver",
  },
  // Hatchbacks
  {
    imageUrl: "/cars/car_types/hatchback/golf.jpeg",
    type: "Hatchback",
    make: "Volkswagen",
    model: "Golf",
    year: "2006",
    color: "white",
  },
  {
    imageUrl: "/cars/car_types/hatchback/mazda3.jpeg",
    type: "Hatchback",
    make: "Mazda",
    model: "Mazda3",
    year: "2010",
    color: "blue",
  },
  {
    imageUrl: "/cars/car_types/hatchback/focus.jpeg",
    type: "Hatchback",
    make: "Ford",
    model: "Focus",
    year: "2012",
    color: "blue",
  },
  {
    imageUrl: "/cars/car_types/hatchback/yaris.jpeg",
    type: "Hatchback",
    make: "Toyota",
    model: "Yaris",
    year: "2021",
    color: "green",
  },
  {
    imageUrl: "/cars/car_types/hatchback/polo.jpeg",
    type: "Hatchback",
    make: "Volkswagen",
    model: "Polo",
    year: "2017",
    color: "pink",
  },
  {
    imageUrl: "/cars/car_types/hatchback/fiesta.jpeg",
    type: "Hatchback",
    make: "Ford",
    model: "Fiesta",
    year: "2018",
    color: "silver",
  },
  // SUVs
  {
    imageUrl: "cars/car_types/suv/cr-v.jpeg",
    type: "SUV",
    make: "Honda",
    model: "CR-V",
    year: "2013",
    color: "black",
  },
  {
    imageUrl: "cars/car_types/suv/rav4.jpeg",
    type: "SUV",
    make: "Toyota",
    model: "Rav4",
    year: "2022",
    color: "silver",
  },
  {
    imageUrl: "cars/car_types/suv/escape.jpeg",
    type: "SUV",
    make: "Ford",
    model: "Escape",
    year: "2000",
    color: "silver",
  },
  {
    imageUrl: "cars/car_types/suv/tiguan.jpeg",
    type: "SUV",
    make: "Volkswagen",
    model: "Tiguan",
    year: "2016",
    color: "white",
  },
  {
    imageUrl: "cars/car_types/suv/qashqai.jpeg",
    type: "SUV",
    make: "Nissan",
    model: "Qashqai",
    year: "2009",
    color: "silver",
  },
  {
    imageUrl: "cars/car_types/suv/tucson.jpeg",
    type: "SUV",
    make: "Hyundai",
    model: "Tucson",
    year: "2011",
    color: "blue",
  },
  // Vans
  {
    imageUrl: "/cars/car_types/van/sienna.jpeg",
    type: "Van",
    make: "Toyota",
    model: "Sienna",
    year: "2020",
    color: "silver",
  },
  {
    imageUrl: "/cars/car_types/van/odyssey.jpeg",
    type: "Van",
    make: "Honda",
    model: "Odyssey",
    year: "2008",
    color: "green",
  },
  {
    imageUrl: "/cars/car_types/van/transit.jpeg",
    type: "Van",
    make: "Ford",
    model: "Transit",
    year: "2010",
    color: "black",
  },
  {
    imageUrl: "/cars/car_types/van/caravan.jpeg",
    type: "Van",
    make: "Dodge",
    model: "Caravan",
    year: "2014",
    color: "yellow",
  },
  {
    imageUrl: "/cars/car_types/van/nv200.jpeg",
    type: "Van",
    make: "Nissan",
    model: "NV200",
    year: "2023",
    color: "pink",
  },
  {
    imageUrl: "/cars/car_types/van/promaster.jpeg",
    type: "Van",
    make: "Ram",
    model: "ProMaster",
    year: "2022",
    color: "green",
  },
  // Utes
  {
    imageUrl: "/cars/car_types/ute/hilux.jpeg",
    type: "Ute",
    make: "Toyota",
    model: "Hilux",
    year: "2004",
    color: "white",
  },
  {
    imageUrl: "/cars/car_types/ute/ranger.jpeg",
    type: "Ute",
    make: "Ford",
    model: "Ranger",
    year: "2012",
    color: "black",
  },
  {
    imageUrl: "/cars/car_types/ute/navara.jpeg",
    type: "Ute",
    make: "Nissan",
    model: "Navara",
    year: "2007",
    color: "green",
  },
  {
    imageUrl: "/cars/car_types/ute/triton.jpeg",
    type: "Ute",
    make: "Mitsubishi",
    model: "Triton",
    year: "2019",
    color: "pink",
  },
  {
    imageUrl: "/cars/car_types/ute/d-max.jpeg",
    type: "Ute",
    make: "Isuzu",
    model: "D-Max",
    year: "2018",
    color: "red",
  },
  {
    imageUrl: "/cars/car_types/ute/bt-50.jpeg",
    type: "Ute",
    make: "Mazda",
    model: "BT-50",
    year: "2021",
    color: "yellow",
  },
];
